# Generated by Django 3.2.15 on 2022-09-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('s', 'Waiter'), ('T', 'Manager')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tablenbr', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('tablenbrseats', models.IntegerField(default=1)),
                ('tablerating', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MidtermExam.employee')),
                ('monthly', models.FloatField(default=20)),
            ],
            bases=('MidtermExam.employee',),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MidtermExam.employee')),
                ('hourlywage', models.FloatField(default=20)),
            ],
            bases=('MidtermExam.employee',),
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('SeatingID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nbr_of_guest', models.CharField(max_length=18)),
                ('StartTimeDate', models.DateField()),
                ('EndTimeDate', models.DateField()),
                ('table', models.ManyToManyField(to='MidtermExam.Table')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.manager')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='TipsEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.FloatField(default=2)),
                ('seating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.seating')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=10)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.waiter')),
            ],
            options={
                'unique_together': {('waiter', 'specialty')},
            },
        ),
    ]
